name: Full CD with Docker

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Log in to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mitanuriel/gosearch:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

        - name: Create SSH key file
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/ssh_key
            chmod 600 ~/.ssh/ssh_key
            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
        - name: Copy Docker-Compose to server
          run: |
            scp -i ~/.ssh/ssh_key ./docker-compose.dev.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST}}:~/GoSearch/

        - name: Check docker installation
          run: |
            ssh -i ~/.ssh/ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            if ! command -v docker &> /dev/null; then
              echo "Could not find docker, installing..."
              sudo apt-get update
              sudo apt-get install ca-certificates curl
              sudo install -m 0755 -d /etc/apt/keyrings
              sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
              sudo chmod a+r /etc/apt/keyrings/docker.asc

              architecture=$(dpkg --print-architecture) 
              codename=$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
              echo "deb [arch=${architecture} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${codename} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            else
              echo "Docker is already installed"
            fi
            EOF
          
        - name: Check docker-compose installation
          run: |
            ssh -i ~/.ssh/ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            if ! command -v docker-compose &> /dev/null; then
              echo "Could not find docker-compose, installing..."
              sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            else
              echo "Docker-compose is already installed"  
            fi
            EOF

        - name: Stop and remove existing container
          run: |
            ssh -i ~/.ssh/ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker stop go-app 2>/dev/null || true
            docker rm go-app 2>/dev/null || true
            EOF

        - name: Add user to Docker group
          run: |
            ssh -i ~/.ssh/ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo usermod -aG docker ${{ secrets.SERVER_USER }}
            EOF

        - name: Deploy to server
          run: |
            ssh -i ~/.ssh/ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            mkdir -p ~/GoSearch
            cd ~/GoSearch
            docker-compose -f docker-compose.dev.yml down -v || true
            docker-compose -f docker-compose.dev.yml pull
            docker-compose -f docker-compose.dev.yml up -d --force-recreate
            EOF

        - name: Clean up Docker resources
          run: |
            ssh -i ~/.ssh/ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker container prune -f
            docker image prune -f
            EOF
